---
- name: Pull Docker Image of Calculator
  hosts: dspani-hppaviliongaminglaptop15ec1xxx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Image
      docker_image:
        name: dspani/devcalc:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running Container
      shell: docker run -it -a --name CalcUlator dspani/devcalc:latest